## This jupyter notebook is for practice coding *numpy* library.
- Start with basic syntax
- Introduce interesting coding
- Build a mini-project

In [4]:
import numpy as np

In [8]:
# linspace
l = np.linspace(2.5, 4.2, 8)
print(l)

[2.5        2.74285714 2.98571429 3.22857143 3.47142857 3.71428571
 3.95714286 4.2       ]


In [6]:
# arange
a = np.arange(2.5, 3.2, 0.2)
print(a)

[2.5 2.7 2.9 3.1]


In [10]:
# empty
e = np.empty((3, 2))
print(e) 

[[-0.00000000e+000 -2.68679316e+154]
 [ 1.48219694e-323  0.00000000e+000]
 [ 0.00000000e+000  4.17201348e-309]]


In [11]:
# reshape
d = np.linspace(1, 10, 10, dtype=int)
a = np.reshape(d, (2, 5))
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [12]:
d = np.arange(0, 0.9, 0.1).reshape((3, 3))
print(d)

[[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]]


In [13]:
# vectors
x = np.linspace(1, 3, 3, dtype=int)
y = np.linspace(5, 8, 3, dtype=int)

# concatenate
print(np.concatenate((x, y)))

[1 2 3 5 6 8]


In [14]:
# repeat and title
print(np.repeat(x, 3))
print(np.tile(x, 3))

[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]


In [15]:
# dot products
a = np.linspace(1, 4, 4, dtype=int)                    # 1x4
b = np.linspace(1, 12, 12, dtype=int).reshape((4, 3))  # 4x3
c = np.linspace(1, 12, 12, dtype=int).reshape((3, 4))  # 3x4
print(a @ b) # same as np.dot(a,b)
print(b @ c)

[70 80 90]
[[ 38  44  50  56]
 [ 83  98 113 128]
 [128 152 176 200]
 [173 206 239 272]]


In [16]:
# list to array
l = [i + i * 4 for i in range(10)]
ar = np.array(l)
print(ar)

[ 0  5 10 15 20 25 30 35 40 45]


In [20]:
# random module
np.random.seed(42)
R = np.random.randn(3)
R1 = np.random.randint(0, 10)
print(R, R1)

[ 0.49671415 -0.1382643   0.64768854] 6


# Mini-project

## Demand Estimation with $n$ Substitutable Products


Write a function called `demand` with two input arguments:

- `prices`: a list of $n$ prices, one for each product. 
- `values`: a list in which each element represents a customer's valuations for the $n$ products. The valuations is a list of length $n$, which corresponds to the customer's willingness to pay for each of the $n$ products.

The function should return a list of length $n$ representing the number of each product sold. You should assume that each customer:

- Does not purchase anything if his/her valuation for each product is strictly less than its price.
- Otherwise, purchase the product in which the difference between his/her valuation and the price is the largest. When there is a tie, the customer will purchase the product with the smaller index. 

For example, if `prices=[10,8,12]`, then

- A customer with valuations `[9,7,11]` purchases nothing.
- A customer with valuations `[10,8,12]` purchases product 1.
- A customer with valuations `[9,8,12]` purchases product 2.
- A customer with valuations `[9,8,13]` purchases product 3.

**Sample run 1:**

```python
prices=[10,8,12]
values=[[9,7,11],[10,8,12],[9,8,12],[9,8,13]]
ans=demand(prices,values)
for i in range(len(prices)):
    print(f'Demand for product {i+1}:',ans[i])
```

**Correct output:**

```
Demand for product 1: 1
Demand for product 2: 1
Demand for product 3: 1
```

**Sample run 2:**

```python
prices=[20,15,30]
values=[[30,30,20],[40,10,15],[18,13,29],[40,30,50],[10,30,50],[10,10,10],[20,15,30]]
ans=demand(prices,values)
for i in range(len(prices)):
    print(f'Demand for product {i+1}:',ans[i])
   ```
   
**Correct output:**

```
Demand for product 1: 3
Demand for product 2: 1
Demand for product 3: 1
```

In [28]:
# using the where and unique method
def demand(prices,values):
    p = np.array(prices)
    v = np.array(values)
    test = v - p 
    count = []
    for i in test:
        mx = i.max()
        # getting the smaller index
        a = np.where(i == mx)[0][0]
        if mx >= 0:
            count.append(a)
    _, counts = np.unique(np.array(count), return_counts=True)
    return counts

In [25]:
# Sample run 1
prices=[10,8,12]
values=[[9,7,11],[10,8,12],[9,8,12],[9,8,13]]
ans=demand(prices,values)
for i in range(len(prices)):
    print('Demand for product',i,':',ans[i])

Demand for product 0 : 1
Demand for product 1 : 1
Demand for product 2 : 1


In [26]:
# Sample run 2
prices=[20,15,30]
values=[[30,30,20],[40,10,15],[18,13,29],[40,30,50],[10,30,50],[10,10,10],[20,15,30]]
ans=demand(prices,values)
for i in range(len(prices)):
    print('Demand for product',i,':',ans[i])

Demand for product 0 : 3
Demand for product 1 : 1
Demand for product 2 : 1


### Spin-off

In [29]:
# all method
p = np.array(prices)
v = np.array(values)
test = v - p 
for i in test:
    mx = i.max()
    tf = np.all(i == mx) 
    # returns a bool, True means that all the value in that vector has the max value
    print(tf)

False
False
False
False
False
False
True
