## This jupyter notebook is for practice coding *numpy* library.
- Start with basic syntax
- Introduce interesting coding
- Build a mini-project

In [4]:
import numpy as np

In [8]:
# linspace
l = np.linspace(2.5, 4.2, 8)
print(l)

[2.5        2.74285714 2.98571429 3.22857143 3.47142857 3.71428571
 3.95714286 4.2       ]


In [6]:
# arange
a = np.arange(2.5, 3.2, 0.2)
print(a)

[2.5 2.7 2.9 3.1]


In [10]:
# empty
e = np.empty((3, 2))
print(e) 

[[-0.00000000e+000 -2.68679316e+154]
 [ 1.48219694e-323  0.00000000e+000]
 [ 0.00000000e+000  4.17201348e-309]]


In [11]:
# reshape
d = np.linspace(1, 10, 10, dtype=int)
a = np.reshape(d, (2, 5))
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [12]:
d = np.arange(0, 0.9, 0.1).reshape((3, 3))
print(d)

[[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]]


In [13]:
# vectors
x = np.linspace(1, 3, 3, dtype=int)
y = np.linspace(5, 8, 3, dtype=int)

# concatenate
print(np.concatenate((x, y)))

[1 2 3 5 6 8]


In [14]:
# repeat and title
print(np.repeat(x, 3))
print(np.tile(x, 3))

[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]


In [15]:
# dot products
a = np.linspace(1, 4, 4, dtype=int)                    # 1x4
b = np.linspace(1, 12, 12, dtype=int).reshape((4, 3))  # 4x3
c = np.linspace(1, 12, 12, dtype=int).reshape((3, 4))  # 3x4
print(a @ b) # same as np.dot(a,b)
print(b @ c)

[70 80 90]
[[ 38  44  50  56]
 [ 83  98 113 128]
 [128 152 176 200]
 [173 206 239 272]]


In [16]:
# list to array
l = [i + i * 4 for i in range(10)]
ar = np.array(l)
print(ar)

[ 0  5 10 15 20 25 30 35 40 45]


In [20]:
# random module
np.random.seed(42)
R = np.random.randn(3)
R1 = np.random.randint(0, 10)
print(R, R1)

[ 0.49671415 -0.1382643   0.64768854] 6
